DELETE http://localhost:3003/api/blogs/68808900cb90de7498ec7e6a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFCQ0QiLCJpZCI6IjY4ODA2ZmI2NTczZTdkZDc4MWVhYWZkZiIsImlhdCI6MTc1MzI1NjgzMiwiZXhwIjoxNzUzMjYwNDMyfQ.qcVvOxEERyINyQjRhUlx7SxvISDXzeC-vadL6fdkQtI
# Authorization: : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFCQ0RFIiwiaWQiOiI2ODgwOWNiNTY0ODg2NDhjMDA5MWI1ZmEiLCJpYXQiOjE3NTMyNTkyMDQsImV4cCI6MTc1MzI2MjgwNH0.8Z91BsEyMyp8OE8NUGnhnXW1Mq637yI_I5NtRmWjXMk